<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DoctorSeeder extends Seeder
{
    public function run(): void
    {
        $doctors = [
            // Cardiology
            [
                'doctor_id' => 'DOC-00001',
                'name' => 'Ahmed Hassan',
                'specialization' => 'Cardiology',
                'qualification' => 'MBBS, FCPS (Cardiology)',
                'phone' => '0300-1234567',
                'email' => 'ahmed.hassan@hospital.pk',
                'cnic' => '1710123456789',
                'gender' => 'Male',
                'department' => 'Cardiology',
                'consultation_fee' => 2500.00,
                'availability' => 'Available',
                'shift' => 'Morning',
                'shift_start' => '09:00:00',
                'shift_end' => '14:00:00',
                'bio' => 'Senior Cardiologist with 15+ years experience in interventional cardiology.',
                'is_active' => true,
            ],
            [
                'doctor_id' => 'DOC-00002',
                'name' => 'Fatima Malik',
                'specialization' => 'Cardiology',
                'qualification' => 'MBBS, MD (Cardiology)',
                'phone' => '0301-2345678',
                'email' => 'fatima.malik@hospital.pk',
                'cnic' => '6110298765432',
                'gender' => 'Female',
                'department' => 'Cardiology',
                'consultation_fee' => 2000.00,
                'availability' => 'Available',
                'shift' => 'Evening',
                'shift_start' => '15:00:00',
                'shift_end' => '20:00:00',
                'bio' => 'Expert in non-invasive cardiac imaging and preventive cardiology.',
                'is_active' => true,
            ],

            // General Medicine
            [
                'doctor_id' => 'DOC-00003',
                'name' => 'Muhammad Tariq',
                'specialization' => 'General Medicine',
                'qualification' => 'MBBS, FCPS (Medicine)',
                'phone' => '0302-3456789',
                'email' => 'tariq@hospital.pk',
                'cnic' => '4210145678901',
                'gender' => 'Male',
                'department' => 'General Medicine',
                'consultation_fee' => 1500.00,
                'availability' => 'Available',
                'shift' => 'Full Day',
                'shift_start' => '08:00:00',
                'shift_end' => '16:00:00',
                'bio' => 'General Physician with expertise in diabetes and hypertension management.',
                'is_active' => true,
            ],
            [
                'doctor_id' => 'DOC-00004',
                'name' => 'Ayesha Siddiqui',
                'specialization' => 'General Medicine',
                'qualification' => 'MBBS, MCPS',
                'phone' => '0303-4567890',
                'email' => 'ayesha.siddiqui@hospital.pk',
                'cnic' => '3520287654321',
                'gender' => 'Female',
                'department' => 'General Medicine',
                'consultation_fee' => 1200.00,
                'availability' => 'Available',
                'shift' => 'Night',
                'shift_start' => '20:00:00',
                'shift_end' => '08:00:00',
                'bio' => 'General Physician specializing in infectious diseases.',
                'is_active' => true,
            ],

            // Pediatrics
            [
                'doctor_id' => 'DOC-00005',
                'name' => 'Zainab Ahmed',
                'specialization' => 'Pediatrics',
                'qualification' => 'MBBS, FCPS (Pediatrics)',
                'phone' => '0304-5678901',
                'email' => 'zainab.ahmed@hospital.pk',
                'cnic' => '1710356789012',
                'gender' => 'Female',
                'department' => 'Pediatrics',
                'consultation_fee' => 1800.00,
                'availability' => 'Available',
                'shift' => 'Morning',
                'shift_start' => '08:00:00',
                'shift_end' => '14:00:00',
                'bio' => 'Pediatrician specializing in neonatal care and child development.',
                'is_active' => true,
            ],
            [
                'doctor_id' => 'DOC-00006',
                'name' => 'Bilal Khan',
                'specialization' => 'Pediatrics',
                'qualification' => 'MBBS, DCH, FCPS',
                'phone' => '0305-6789012',
                'email' => 'bilal.khan@hospital.pk',
                'cnic' => '4210456789123',
                'gender' => 'Male',
                'department' => 'Pediatrics',
                'consultation_fee' => 1600.00,
                'availability' => 'Available',
                'shift' => 'Evening',
                'shift_start' => '14:00:00',
                'shift_end' => '20:00:00',
                'bio' => 'Child specialist with focus on respiratory diseases in children.',
                'is_active' => true,
            ],

            // Gynecology
            [
                'doctor_id' => 'DOC-00007',
                'name' => 'Sana Farooq',
                'specialization' => 'Gynecology',
                'qualification' => 'MBBS, FCPS (Gynae)',
                'phone' => '0306-7890123',
                'email' => 'sana.farooq@hospital.pk',
                'cnic' => '6110478901234',
                'gender' => 'Female',
                'department' => 'Gynecology & Obstetrics',
                'consultation_fee' => 2200.00,
                'availability' => 'Available',
                'shift' => 'Morning',
                'shift_start' => '09:00:00',
                'shift_end' => '15:00:00',
                'bio' => 'Obstetrician & Gynecologist with expertise in high-risk pregnancies.',
                'is_active' => true,
            ],

            // Orthopedics
            [
                'doctor_id' => 'DOC-00008',
                'name' => 'Imran Rasheed',
                'specialization' => 'Orthopedics',
                'qualification' => 'MBBS, FCPS (Orthopedics)',
                'phone' => '0307-8901234',
                'email' => 'imran.rasheed@hospital.pk',
                'cnic' => '3520589012345',
                'gender' => 'Male',
                'department' => 'Orthopedics',
                'consultation_fee' => 2000.00,
                'availability' => 'Available',
                'shift' => 'Morning',
                'shift_start' => '08:00:00',
                'shift_end' => '14:00:00',
                'bio' => 'Orthopedic surgeon specializing in joint replacement and sports injuries.',
                'is_active' => true,
            ],

            // Dermatology
            [
                'doctor_id' => 'DOC-00009',
                'name' => 'Hina Javed',
                'specialization' => 'Dermatology',
                'qualification' => 'MBBS, FCPS (Dermatology)',
                'phone' => '0308-9012345',
                'email' => 'hina.javed@hospital.pk',
                'cnic' => '1710690123456',
                'gender' => 'Female',
                'department' => 'Dermatology',
                'consultation_fee' => 1800.00,
                'availability' => 'Available',
                'shift' => 'Evening',
                'shift_start' => '15:00:00',
                'shift_end' => '20:00:00',
                'bio' => 'Dermatologist specializing in cosmetic dermatology and skin disorders.',
                'is_active' => true,
            ],

            // ENT
            [
                'doctor_id' => 'DOC-00010',
                'name' => 'Usman Ali',
                'specialization' => 'ENT',
                'qualification' => 'MBBS, FCPS (ENT)',
                'phone' => '0309-0123456',
                'email' => 'usman.ali@hospital.pk',
                'cnic' => '4210701234567',
                'gender' => 'Male',
                'department' => 'ENT',
                'consultation_fee' => 1700.00,
                'availability' => 'Available',
                'shift' => 'Morning',
                'shift_start' => '09:00:00',
                'shift_end' => '14:00:00',
                'bio' => 'ENT specialist with expertise in sinus surgeries and hearing disorders.',
                'is_active' => true,
            ],

            // Neurology
            [
                'doctor_id' => 'DOC-00011',
                'name' => 'Saad Mahmood',
                'specialization' => 'Neurology',
                'qualification' => 'MBBS, FCPS (Neurology)',
                'phone' => '0310-1234567',
                'email' => 'saad.mahmood@hospital.pk',
                'cnic' => '6110812345678',
                'gender' => 'Male',
                'department' => 'Neurology',
                'consultation_fee' => 2800.00,
                'availability' => 'Available',
                'shift' => 'Full Day',
                'shift_start' => '08:00:00',
                'shift_end' => '16:00:00',
                'bio' => 'Neurologist specializing in stroke management and epilepsy.',
                'is_active' => true,
            ],

            // Psychiatry
            [
                'doctor_id' => 'DOC-00012',
                'name' => 'Amna Yousaf',
                'specialization' => 'Psychiatry',
                'qualification' => 'MBBS, FCPS (Psychiatry)',
                'phone' => '0311-2345678',
                'email' => 'amna.yousaf@hospital.pk',
                'cnic' => '3520923456789',
                'gender' => 'Female',
                'department' => 'Psychiatry',
                'consultation_fee' => 2500.00,
                'availability' => 'Available',
                'shift' => 'Evening',
                'shift_start' => '14:00:00',
                'shift_end' => '20:00:00',
                'bio' => 'Psychiatrist specializing in anxiety, depression and cognitive behavioral therapy.',
                'is_active' => true,
            ],

            // Emergency Medicine
            [
                'doctor_id' => 'DOC-00013',
                'name' => 'Kashif Raza',
                'specialization' => 'Emergency Medicine',
                'qualification' => 'MBBS, FCPS (Emergency)',
                'phone' => '0312-3456789',
                'email' => 'kashif.raza@hospital.pk',
                'cnic' => '1711034567890',
                'gender' => 'Male',
                'department' => 'Emergency',
                'consultation_fee' => 1500.00,
                'availability' => 'Available',
                'shift' => 'Night',
                'shift_start' => '20:00:00',
                'shift_end' => '08:00:00',
                'bio' => 'Emergency physician with expertise in trauma and critical care.',
                'is_active' => true,
            ],

            // Radiology
            [
                'doctor_id' => 'DOC-00014',
                'name' => 'Nadia Iqbal',
                'specialization' => 'Radiology',
                'qualification' => 'MBBS, FCPS (Radiology)',
                'phone' => '0313-4567890',
                'email' => 'nadia.iqbal@hospital.pk',
                'cnic' => '4211145678901',
                'gender' => 'Female',
                'department' => 'Radiology',
                'consultation_fee' => 2000.00,
                'availability' => 'Available',
                'shift' => 'Full Day',
                'shift_start' => '08:00:00',
                'shift_end' => '16:00:00',
                'bio' => 'Radiologist specializing in CT and MRI interpretation.',
                'is_active' => true,
            ],

            // Oncology
            [
                'doctor_id' => 'DOC-00015',
                'name' => 'Hassan Nawaz',
                'specialization' => 'Oncology',
                'qualification' => 'MBBS, FCPS (Oncology)',
                'phone' => '0314-5678901',
                'email' => 'hassan.nawaz@hospital.pk',
                'cnic' => '6111256789012',
                'gender' => 'Male',
                'department' => 'Oncology',
                'consultation_fee' => 3000.00,
                'availability' => 'Available',
                'shift' => 'Morning',
                'shift_start' => '09:00:00',
                'shift_end' => '14:00:00',
                'bio' => 'Medical oncologist specializing in chemotherapy and cancer care.',
                'is_active' => true,
            ],
        ];

        foreach ($doctors as $doctor) {
            DB::table('doctors')->insert(array_merge($doctor, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ 15 Doctors seeded successfully');
    }
}