<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            // Pain & Fever
            [
                'medicine_code' => 'MED-00001',
                'name' => 'Panadol',
                'generic_name' => 'Paracetamol',
                'brand' => 'GSK',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 1.50,
                'sale_price' => 2.00,
                'reorder_level' => 50,
                'total_stock' => 500,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => '500mg Paracetamol tablet for pain and fever',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00002',
                'name' => 'Brufen',
                'generic_name' => 'Ibuprofen',
                'brand' => 'Abbott',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 3.00,
                'sale_price' => 4.50,
                'reorder_level' => 40,
                'total_stock' => 300,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '400mg Ibuprofen anti-inflammatory',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00003',
                'name' => 'Disprin',
                'generic_name' => 'Aspirin',
                'brand' => 'Reckitt Benckiser',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 1.00,
                'sale_price' => 1.50,
                'reorder_level' => 30,
                'total_stock' => 250,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => 'Soluble Aspirin 300mg',
                'is_active' => true,
            ],

            // Antibiotics
            [
                'medicine_code' => 'MED-00004',
                'name' => 'Augmentin',
                'generic_name' => 'Amoxicillin + Clavulanic Acid',
                'brand' => 'GSK',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 15.00,
                'sale_price' => 22.00,
                'reorder_level' => 30,
                'total_stock' => 200,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '625mg antibiotic for bacterial infections',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00005',
                'name' => 'Ciproxin',
                'generic_name' => 'Ciprofloxacin',
                'brand' => 'Bayer',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 12.00,
                'sale_price' => 18.00,
                'reorder_level' => 25,
                'total_stock' => 150,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '500mg Fluoroquinolone antibiotic',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00006',
                'name' => 'Zithromax',
                'generic_name' => 'Azithromycin',
                'brand' => 'Pfizer',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 25.00,
                'sale_price' => 35.00,
                'reorder_level' => 20,
                'total_stock' => 100,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '500mg Macrolide antibiotic',
                'is_active' => true,
            ],

            // Diabetes
            [
                'medicine_code' => 'MED-00007',
                'name' => 'Glucophage',
                'generic_name' => 'Metformin',
                'brand' => 'Merck',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 8.00,
                'sale_price' => 12.00,
                'reorder_level' => 40,
                'total_stock' => 400,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '500mg for Type 2 Diabetes',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00008',
                'name' => 'Insulin Mixtard',
                'generic_name' => 'Human Insulin',
                'brand' => 'Novo Nordisk',
                'category' => 'Injection',
                'unit' => 'Vial',
                'purchase_price' => 850.00,
                'sale_price' => 1100.00,
                'reorder_level' => 10,
                'total_stock' => 50,
                'requires_prescription' => true,
                'storage_condition' => 'Refrigerate (2-8°C)',
                'description' => '100IU/ml Insulin for diabetes',
                'is_active' => true,
            ],

            // Blood Pressure
            [
                'medicine_code' => 'MED-00009',
                'name' => 'Concor',
                'generic_name' => 'Bisoprolol',
                'brand' => 'Merck',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 10.00,
                'sale_price' => 15.00,
                'reorder_level' => 30,
                'total_stock' => 250,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '5mg Beta-blocker for hypertension',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00010',
                'name' => 'Norvasc',
                'generic_name' => 'Amlodipine',
                'brand' => 'Pfizer',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 8.00,
                'sale_price' => 12.00,
                'reorder_level' => 35,
                'total_stock' => 300,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '5mg Calcium channel blocker',
                'is_active' => true,
            ],

            // Gastric
            [
                'medicine_code' => 'MED-00011',
                'name' => 'Risek',
                'generic_name' => 'Omeprazole',
                'brand' => 'Getz Pharma',
                'category' => 'Capsule',
                'unit' => 'Capsule',
                'purchase_price' => 6.00,
                'sale_price' => 9.00,
                'reorder_level' => 50,
                'total_stock' => 400,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '20mg PPI for acid reflux',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00012',
                'name' => 'Motilium',
                'generic_name' => 'Domperidone',
                'brand' => 'Sanofi',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 4.00,
                'sale_price' => 6.00,
                'reorder_level' => 30,
                'total_stock' => 200,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '10mg for nausea and vomiting',
                'is_active' => true,
            ],

            // Cough & Cold
            [
                'medicine_code' => 'MED-00013',
                'name' => 'Rexcof',
                'generic_name' => 'Dextromethorphan + Phenylephrine',
                'brand' => 'PharmEvo',
                'category' => 'Syrup',
                'unit' => 'Bottle (120ml)',
                'purchase_price' => 80.00,
                'sale_price' => 120.00,
                'reorder_level' => 20,
                'total_stock' => 100,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => 'Cough syrup for dry cough',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00014',
                'name' => 'Cetrine',
                'generic_name' => 'Cetirizine',
                'brand' => 'GSK',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 2.00,
                'sale_price' => 3.00,
                'reorder_level' => 40,
                'total_stock' => 350,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => '10mg Antihistamine for allergies',
                'is_active' => true,
            ],

            // Vitamins & Supplements
            [
                'medicine_code' => 'MED-00015',
                'name' => 'Neurobion Forte',
                'generic_name' => 'Vitamin B Complex',
                'brand' => 'P&G Health',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 5.00,
                'sale_price' => 7.50,
                'reorder_level' => 30,
                'total_stock' => 250,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => 'B1, B6, B12 vitamin supplement',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00016',
                'name' => 'Ferose',
                'generic_name' => 'Ferrous Sulfate',
                'brand' => 'GSK',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 3.00,
                'sale_price' => 4.50,
                'reorder_level' => 35,
                'total_stock' => 300,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => 'Iron supplement for anemia',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00017',
                'name' => 'Calcium Sandoz',
                'generic_name' => 'Calcium Carbonate',
                'brand' => 'Novartis',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 4.00,
                'sale_price' => 6.00,
                'reorder_level' => 30,
                'total_stock' => 200,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => 'Calcium supplement',
                'is_active' => true,
            ],

            // Pediatric
            [
                'medicine_code' => 'MED-00018',
                'name' => 'Calpol Syrup',
                'generic_name' => 'Paracetamol',
                'brand' => 'GSK',
                'category' => 'Syrup',
                'unit' => 'Bottle (60ml)',
                'purchase_price' => 45.00,
                'sale_price' => 65.00,
                'reorder_level' => 25,
                'total_stock' => 150,
                'requires_prescription' => false,
                'storage_condition' => 'Room Temperature',
                'description' => 'Paracetamol 120mg/5ml for children',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00019',
                'name' => 'Amoxil Drops',
                'generic_name' => 'Amoxicillin',
                'brand' => 'GSK',
                'category' => 'Drops',
                'unit' => 'Bottle (15ml)',
                'purchase_price' => 120.00,
                'sale_price' => 180.00,
                'reorder_level' => 15,
                'total_stock' => 80,
                'requires_prescription' => true,
                'storage_condition' => 'Refrigerate after opening',
                'description' => 'Antibiotic drops for children',
                'is_active' => true,
            ],

            // Emergency & Injectable
            [
                'medicine_code' => 'MED-00020',
                'name' => 'Adrenaline Injection',
                'generic_name' => 'Epinephrine',
                'brand' => 'Pfizer',
                'category' => 'Injection',
                'unit' => 'Ampule',
                'purchase_price' => 50.00,
                'sale_price' => 75.00,
                'reorder_level' => 20,
                'total_stock' => 100,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature, Protect from Light',
                'description' => '1mg/ml for emergency use',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00021',
                'name' => 'Lasix Injection',
                'generic_name' => 'Furosemide',
                'brand' => 'Sanofi',
                'category' => 'Injection',
                'unit' => 'Ampule',
                'purchase_price' => 30.00,
                'sale_price' => 45.00,
                'reorder_level' => 25,
                'total_stock' => 120,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature, Protect from Light',
                'description' => '20mg/2ml Diuretic injection',
                'is_active' => true,
            ],

            // More Common Medicines
            [
                'medicine_code' => 'MED-00022',
                'name' => 'Flagyl',
                'generic_name' => 'Metronidazole',
                'brand' => 'Sanofi',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 6.00,
                'sale_price' => 9.00,
                'reorder_level' => 30,
                'total_stock' => 200,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '400mg Antibiotic for anaerobic infections',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00023',
                'name' => 'Lipitor',
                'generic_name' => 'Atorvastatin',
                'brand' => 'Pfizer',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 15.00,
                'sale_price' => 22.00,
                'reorder_level' => 25,
                'total_stock' => 180,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => '20mg Statin for cholesterol',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00024',
                'name' => 'Ventolin Inhaler',
                'generic_name' => 'Salbutamol',
                'brand' => 'GSK',
                'category' => 'Inhaler',
                'unit' => 'Inhaler',
                'purchase_price' => 450.00,
                'sale_price' => 650.00,
                'reorder_level' => 10,
                'total_stock' => 60,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature',
                'description' => 'Bronchodilator for asthma',
                'is_active' => true,
            ],
            [
                'medicine_code' => 'MED-00025',
                'name' => 'Xanax',
                'generic_name' => 'Alprazolam',
                'brand' => 'Pfizer',
                'category' => 'Tablet',
                'unit' => 'Tablet',
                'purchase_price' => 8.00,
                'sale_price' => 12.00,
                'reorder_level' => 20,
                'total_stock' => 100,
                'requires_prescription' => true,
                'storage_condition' => 'Room Temperature, Controlled Substance',
                'description' => '0.5mg for anxiety disorders',
                'is_active' => true,
            ],
        ];

        foreach ($medicines as $medicine) {
            DB::table('medicines')->insert(array_merge($medicine, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ 25 Medicines seeded successfully');
    }
}