<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            // OPD Patients
            [
                'mrn' => 'MRN-00001',
                'name' => 'Ali Raza',
                'father_name' => 'Raza Ahmed',
                'date_of_birth' => '1985-03-15',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'phone' => '0321-1234567',
                'emergency_contact' => '0322-1234567',
                'emergency_relation' => 'Brother',
                'cnic' => '4210112345671',
                'address' => 'House # 45, Street 7, Satellite Town',
                'city' => 'Rawalpindi',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 3,
                'notes' => 'Diabetic patient, regular follow-up required',
            ],
            [
                'mrn' => 'MRN-00002',
                'name' => 'Fatima Khan',
                'father_name' => 'Khan Sahib',
                'date_of_birth' => '1992-07-22',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'phone' => '0333-2345678',
                'emergency_contact' => '0334-2345678',
                'emergency_relation' => 'Husband',
                'cnic' => '6110223456782',
                'address' => 'Flat 12, Al-Noor Plaza, Blue Area',
                'city' => 'Islamabad',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 7,
                'notes' => 'Expecting mother, 2nd trimester',
            ],
            [
                'mrn' => 'MRN-00003',
                'name' => 'Hassan Ali',
                'father_name' => 'Ali Ahmed',
                'date_of_birth' => '1978-11-08',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'phone' => '0300-3456789',
                'emergency_contact' => '0301-3456789',
                'emergency_relation' => 'Wife',
                'cnic' => '1710334567893',
                'address' => 'House 78, Gulberg Colony',
                'city' => 'Peshawar',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 1,
                'notes' => 'Cardiac patient, hypertension',
            ],
            [
                'mrn' => 'MRN-00004',
                'name' => 'Ayesha Bibi',
                'father_name' => 'Muhammad Yousaf',
                'date_of_birth' => '2000-05-12',
                'gender' => 'Female',
                'blood_group' => 'AB+',
                'phone' => '0345-4567890',
                'emergency_contact' => '0346-4567890',
                'emergency_relation' => 'Father',
                'cnic' => '3520445678904',
                'address' => 'Mohalla Islamia, near City Hospital',
                'city' => 'Multan',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 9,
                'notes' => 'Skin allergy, prescribed antihistamines',
            ],
            [
                'mrn' => 'MRN-00005',
                'name' => 'Zain Abbas',
                'father_name' => 'Abbas Ali',
                'date_of_birth' => '2015-09-20',
                'gender' => 'Male',
                'blood_group' => 'B-',
                'phone' => '0312-5678901',
                'emergency_contact' => '0313-5678901',
                'emergency_relation' => 'Mother',
                'cnic' => null,
                'address' => 'Street 12, Johar Town',
                'city' => 'Lahore',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 5,
                'notes' => 'Child patient, asthma history',
            ],

            // IPD Patients
            [
                'mrn' => 'MRN-00006',
                'name' => 'Kamran Hussain',
                'father_name' => 'Hussain Shah',
                'date_of_birth' => '1965-02-14',
                'gender' => 'Male',
                'blood_group' => 'A-',
                'phone' => '0320-6789012',
                'emergency_contact' => '0321-6789012',
                'emergency_relation' => 'Son',
                'cnic' => '4210556789015',
                'address' => 'Village Chak 45, Sargodha Road',
                'city' => 'Sargodha',
                'patient_type' => 'IPD',
                'status' => 'Admitted',
                'doctor_id' => 1,
                'notes' => 'Admitted for cardiac surgery, pre-op evaluation done',
            ],
            [
                'mrn' => 'MRN-00007',
                'name' => 'Sadia Malik',
                'father_name' => 'Malik Aslam',
                'date_of_birth' => '1988-08-30',
                'gender' => 'Female',
                'blood_group' => 'O-',
                'phone' => '0332-7890123',
                'emergency_contact' => '0333-7890123',
                'emergency_relation' => 'Husband',
                'cnic' => '6110667890126',
                'address' => 'DHA Phase 5, House 234',
                'city' => 'Karachi',
                'patient_type' => 'IPD',
                'status' => 'Admitted',
                'doctor_id' => 7,
                'notes' => 'C-section scheduled for tomorrow',
            ],
            [
                'mrn' => 'MRN-00008',
                'name' => 'Bilal Ahmed',
                'father_name' => 'Ahmed Khan',
                'date_of_birth' => '1995-01-18',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'phone' => '0344-8901234',
                'emergency_contact' => '0345-8901234',
                'emergency_relation' => 'Father',
                'cnic' => '1710778901237',
                'address' => 'Board Bazaar, near Mosque',
                'city' => 'Peshawar',
                'patient_type' => 'IPD',
                'status' => 'Admitted',
                'doctor_id' => 8,
                'notes' => 'Admitted after road accident, fractured leg',
            ],

            // More OPD Patients
            [
                'mrn' => 'MRN-00009',
                'name' => 'Nadia Farooq',
                'father_name' => 'Farooq Ahmed',
                'date_of_birth' => '1983-12-05',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'phone' => '0315-9012345',
                'emergency_contact' => '0316-9012345',
                'emergency_relation' => 'Sister',
                'cnic' => '3520889012348',
                'address' => 'Garden Town, Block B',
                'city' => 'Faisalabad',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 11,
                'notes' => 'Migraine patient, monthly consultation',
            ],
            [
                'mrn' => 'MRN-00010',
                'name' => 'Imran Khalid',
                'father_name' => 'Khalid Mehmood',
                'date_of_birth' => '1970-06-25',
                'gender' => 'Male',
                'blood_group' => 'AB-',
                'phone' => '0302-0123456',
                'emergency_contact' => '0303-0123456',
                'emergency_relation' => 'Wife',
                'cnic' => '4210990123459',
                'address' => 'Westridge, House 567',
                'city' => 'Rawalpindi',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 3,
                'notes' => 'Hypertension and cholesterol issues',
            ],
            [
                'mrn' => 'MRN-00011',
                'name' => 'Sara Khan',
                'father_name' => 'Khan Mohammad',
                'date_of_birth' => '2010-03-14',
                'gender' => 'Female',
                'blood_group' => 'O+',
                'phone' => '0335-1234567',
                'emergency_contact' => '0336-1234567',
                'emergency_relation' => 'Mother',
                'cnic' => null,
                'address' => 'Model Town, Street 15',
                'city' => 'Lahore',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 6,
                'notes' => 'Fever and cough, under observation',
            ],
            [
                'mrn' => 'MRN-00012',
                'name' => 'Usman Shah',
                'father_name' => 'Shah Nawaz',
                'date_of_birth' => '1998-09-09',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'phone' => '0340-2345678',
                'emergency_contact' => '0341-2345678',
                'emergency_relation' => 'Father',
                'cnic' => '6111101234560',
                'address' => 'Nazimabad Block 3',
                'city' => 'Karachi',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 10,
                'notes' => 'Ear infection, antibiotics prescribed',
            ],
            [
                'mrn' => 'MRN-00013',
                'name' => 'Mariam Ali',
                'father_name' => 'Ali Akbar',
                'date_of_birth' => '1990-11-22',
                'gender' => 'Female',
                'blood_group' => 'A-',
                'phone' => '0318-3456789',
                'emergency_contact' => '0319-3456789',
                'emergency_relation' => 'Husband',
                'cnic' => '1711212345671',
                'address' => 'University Town, Phase 2',
                'city' => 'Peshawar',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 12,
                'notes' => 'Anxiety disorder, therapy sessions ongoing',
            ],
            [
                'mrn' => 'MRN-00014',
                'name' => 'Faisal Mehmood',
                'father_name' => 'Mehmood Khan',
                'date_of_birth' => '1975-04-17',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'phone' => '0325-4567890',
                'emergency_contact' => '0326-4567890',
                'emergency_relation' => 'Brother',
                'cnic' => '3521323456782',
                'address' => 'Gulshan Colony, near Market',
                'city' => 'Quetta',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 3,
                'notes' => 'Type 2 diabetes, insulin therapy',
            ],
            [
                'mrn' => 'MRN-00015',
                'name' => 'Hina Aslam',
                'father_name' => 'Aslam Pervaiz',
                'date_of_birth' => '2005-07-08',
                'gender' => 'Female',
                'blood_group' => 'AB+',
                'phone' => '0337-5678901',
                'emergency_contact' => '0338-5678901',
                'emergency_relation' => 'Mother',
                'cnic' => null,
                'address' => 'Cantt Area, House 89',
                'city' => 'Sialkot',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 5,
                'notes' => 'Vaccination schedule, routine checkup',
            ],

            // Emergency Patients
            [
                'mrn' => 'MRN-00016',
                'name' => 'Asad Rauf',
                'father_name' => 'Rauf Ahmed',
                'date_of_birth' => '1982-10-30',
                'gender' => 'Male',
                'blood_group' => 'A+',
                'phone' => '0342-6789012',
                'emergency_contact' => '0343-6789012',
                'emergency_relation' => 'Wife',
                'cnic' => '4211434567893',
                'address' => 'Saddar Bazaar Area',
                'city' => 'Rawalpindi',
                'patient_type' => 'Emergency',
                'status' => 'Active',
                'doctor_id' => 13,
                'notes' => 'Admitted via emergency - severe chest pain',
            ],
            [
                'mrn' => 'MRN-00017',
                'name' => 'Saima Batool',
                'father_name' => 'Abdul Rasheed',
                'date_of_birth' => '1995-02-28',
                'gender' => 'Female',
                'blood_group' => 'B-',
                'phone' => '0350-7890123',
                'emergency_contact' => '0351-7890123',
                'emergency_relation' => 'Father',
                'cnic' => '6111545678904',
                'address' => 'Gulistan Colony',
                'city' => 'Hyderabad',
                'patient_type' => 'Emergency',
                'status' => 'Discharged',
                'doctor_id' => 13,
                'notes' => 'Treated for food poisoning, discharged next day',
            ],
            [
                'mrn' => 'MRN-00018',
                'name' => 'Tariq Jameel',
                'father_name' => 'Jameel Ahmed',
                'date_of_birth' => '1968-08-15',
                'gender' => 'Male',
                'blood_group' => 'O-',
                'phone' => '0355-8901234',
                'emergency_contact' => '0356-8901234',
                'emergency_relation' => 'Son',
                'cnic' => '1711656789015',
                'address' => 'Old City, Mohalla Pakhtunabad',
                'city' => 'Peshawar',
                'patient_type' => 'Emergency',
                'status' => 'Admitted',
                'doctor_id' => 13,
                'notes' => 'Stroke patient, under observation in ICU',
            ],
            [
                'mrn' => 'MRN-00019',
                'name' => 'Rabia Noor',
                'father_name' => 'Noor Khan',
                'date_of_birth' => '2018-12-01',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'phone' => '0360-9012345',
                'emergency_contact' => '0361-9012345',
                'emergency_relation' => 'Mother',
                'cnic' => null,
                'address' => 'Defence Phase 6',
                'city' => 'Karachi',
                'patient_type' => 'Emergency',
                'status' => 'Discharged',
                'doctor_id' => 5,
                'notes' => 'High fever emergency, stabilized and discharged',
            ],
            [
                'mrn' => 'MRN-00020',
                'name' => 'Kashif Raza',
                'father_name' => 'Raza Ali',
                'date_of_birth' => '1987-05-19',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'phone' => '0365-0123456',
                'emergency_contact' => '0366-0123456',
                'emergency_relation' => 'Brother',
                'cnic' => '3521767890126',
                'address' => 'Satellite Town, Block F',
                'city' => 'Gujranwala',
                'patient_type' => 'OPD',
                'status' => 'Active',
                'doctor_id' => 15,
                'notes' => 'Cancer screening, biopsy results pending',
            ],
        ];

        foreach ($patients as $patient) {
            DB::table('patients')->insert(array_merge($patient, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ 20 Patients seeded successfully');
    }
}